language: objective-c  #1
osx_image: xcode7.3 #2
xcode_project: EPCalendar.xcodeproj #3
xcode_scheme: EPCalendar #4
xcode_sdk: iphonesimulator #5
script:
- xcodebuild -project EPCalendar.xcodeproj -scheme EPCalendar -sdk iphonesimulator build test
#https://github.com/ipraba/EPCalendarPicker
